library(leaflet)

# Choices for drop-downs
nationality <- c(
  "Afghan"="afghan",
  "Albanian"="albanian",
  "Algerian"="algerian",
  "American"="american",
  "Andorran"="andorran",
  "Angolan"="angolan",
  "Antiguans"="antiguans",
  "Argentinean"="argentinean",
  "Armenian"="armenian",
  "Australian"="australian",
  "Austrian"="austrian",
  "Azerbaijani"="azerbaijani",
  "Bahamian"="bahamian",
  "Bahraini"="bahraini",
  "Bangladeshi"="bangladeshi",
  "Barbadian"="barbadian",
  "Barbudans"="barbudans",
  "Batswana"="batswana",
  "Belarusian"="belarusian",
  "Belgian"="belgian",
  "Belizean"="belizean",
  "Beninese"="beninese",
  "Bhutanese"="bhutanese",
  "Bolivian"="bolivian",
  "Bosnian"="bosnian",
  "Brazilian"="brazilian",
  "British"="british",
  "Bruneian"="bruneian",
  "Bulgarian"="bulgarian",
  "Burkinabe"="burkinabe",
  "Burmese"="burmese",
  "Burundian"="burundian",
  "Cambodian"="cambodian",
  "Cameroonian"="cameroonian",
  "Canadian"="canadian",
  "Cape Verdean"="cape verdean",
  "Central African"="central african",
  "Chadian"="chadian",
  "Chilean"="chilean",
  "Chinese"="chinese",
  "Colombian"="colombian",
  "Comoran"="comoran",
  "Congolese"="congolese",
  "Costa Rican"="costa rican",
  "Croatian"="croatian",
  "Cuban"="cuban",
  "Cypriot"="cypriot",
  "Czech"="czech",
  "Danish"="danish",
  "Djibouti"="djibouti",
  "Dominican"="dominican",
  "Dutch"="dutch",
  "East Timorese"="east timorese",
  "Ecuadorean"="ecuadorean",
  "Egyptian"="egyptian",
  "Emirian"="emirian",
  "Equatorial Guinean"="equatorial guinean",
  "Eritrean"="eritrean",
  "Estonian"="estonian",
  "Ethiopian"="ethiopian",
  "Fijian"="fijian",
  "Filipino"="filipino",
  "Finnish"="finnish",
  "French"="french",
  "Gabonese"="gabonese",
  "Gambian"="gambian",
  "Georgian"="georgian",
  "German"="german",
  "Ghanaian"="ghanaian",
  "Greek"="greek",
  "Grenadian"="grenadian",
  "Guatemalan"="guatemalan",
  "Guinea-Bissauan"="guinea-bissauan",
  "Guinean"="guinean",
  "Guyanese"="guyanese",
  "Haitian"="haitian",
  "Herzegovinian"="herzegovinian",
  "Honduran"="honduran",
  "Hungarian"="hungarian",
  "Icelander"="icelander",
  "Indian"="indian",
  "Indonesian"="indonesian",
  "Iranian"="iranian",
  "Iraqi"="iraqi",
  "Irish"="irish",
  "Israeli"="israeli",
  "Italian"="italian",
  "Ivorian"="ivorian",
  "Jamaican"="jamaican",
  "Japanese"="japanese",
  "Jordanian"="jordanian",
  "Kazakhstani"="kazakhstani",
  "Kenyan"="kenyan",
  "Kittian and Nevisian"="kittian and nevisian",
  "Kuwaiti"="kuwaiti",
  "Kyrgyz"="kyrgyz",
  "Laotian"="laotian",
  "Latvian"="latvian",
  "Lebanese"="lebanese",
  "Liberian"="liberian",
  "Libyan"="libyan",
  "Liechtensteiner"="liechtensteiner",
  "Lithuanian"="lithuanian",
  "Luxembourger"="luxembourger",
  "Macedonian"="macedonian",
  "Malagasy"="malagasy",
  "Malawian"="malawian",
  "Malaysian"="malaysian",
  "Maldivan"="maldivan",
  "Malian"="malian",
  "Maltese"="maltese",
  "Marshallese"="marshallese",
  "Mauritanian"="mauritanian",
  "Mauritian"="mauritian",
  "Mexican"="mexican",
  "Micronesian"="micronesian",
  "Moldovan"="moldovan",
  "Monacan"="monacan",
  "Mongolian"="mongolian",
  "Moroccan"="moroccan",
  "Mosotho"="mosotho",
  "Motswana"="motswana",
  "Mozambican"="mozambican",
  "Namibian"="namibian",
  "Nauruan"="nauruan",
  "Nepalese"="nepalese",
  "New Zealander"="new zealander",
  "Ni-Vanuatu"="ni-vanuatu",
  "Nicaraguan"="nicaraguan",
  "Nigerien"="nigerien",
  "North Korean"="north korean",
  "Northern Irish"="northern irish",
  "Norwegian"="norwegian",
  "Omani"="omani",
  "Pakistani"="pakistani",
  "Palauan"="palauan",
  "Panamanian"="panamanian",
  "Papua New Guinean"="papua new guinean",
  "Paraguayan"="paraguayan",
  "Peruvian"="peruvian",
  "Polish"="polish",
  "Portuguese"="portuguese",
  "Qatari"="qatari",
  "Romanian"="romanian",
  "Russian"="russian",
  "Rwandan"="rwandan",
  "Saint Lucian"="saint lucian",
  "Salvadoran"="salvadoran",
  "Samoan"="samoan",
  "San Marinese"="san marinese",
  "Sao Tomean"="sao tomean",
  "Saudi"="saudi",
  "Scottish"="scottish",
  "Senegalese"="senegalese",
  "Serbian"="serbian",
  "Seychellois"="seychellois",
  "Sierra Leonean"="sierra leonean",
  "Singaporean"="singaporean",
  "Slovakian"="slovakian",
  "Slovenian"="slovenian",
  "Solomon Islander"="solomon islander",
  "Somali"="somali",
  "South African"="south african",
  "South Korean"="south korean",
  "Spanish"="spanish",
  "Sri Lankan"="sri lankan",
  "Sudanese"="sudanese",
  "Surinamer"="surinamer",
  "Swazi"="swazi",
  "Swedish"="swedish",
  "Swiss"="swiss",
  "Syrian"="syrian",
  "Taiwanese"="taiwanese",
  "Tajik"="tajik",
  "Tanzanian"="tanzanian",
  "Thai"="thai",
  "Togolese"="togolese",
  "Tongan"="tongan",
  "Trinidadian or Tobagonian"="trinidadian or tobagonian",
  "Tunisian"="tunisian",
  "Turkish"="turkish",
  "Tuvaluan"="tuvaluan",
  "Ugandan"="ugandan",
  "Ukrainian"="ukrainian",
  "Uruguayan"="uruguayan",
  "Uzbekistani"="uzbekistani",
  "Venezuelan"="venezuelan",
  "Vietnamese"="vietnamese",
  "Welsh"="welsh",
  "Yemenite"="yemenite",
  "Zambian"="zambian",
  "Zimbabwean"="zimbabwean"
  
)

year <- c(
  "Year 1"="year1",
  "Year 2"="year2",
  "Year 3"="year3",
  "Year 4"="year4",
  "Year 5"="year5"
 
  
)


school <- c(
  "School of Accountancy"="SOA",
  "Lee Kong Chian School of Business"="SOB",
  "School of Economics"="SOE",
  "School of Social Sciences"="SOSS",
  "School of Law"="SOL",
  "School of Information Systems" = "SIS"
  
  
)


navbarPage("2019 Spring Exchange", id="nav",
           
           tabPanel("Interactive map",
                    div(class="outer",
                        
                        tags$head(
                          # Include our custom CSS
                          includeCSS("styles.css"),
                          includeScript("gomap.js")
                        ),
                        
                        # If not using custom CSS, set height of leafletOutput to a number instead of percent
                        leafletOutput("map", width="100%", height="100%"),
                        
                        # Shiny versions prior to 0.11 should use class = "modal" instead.
                        absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                      draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto",
                                      width = 330, height = "auto",
                                      
                                      #h2("ZIP explorer"),
                                      
                                      selectInput("nationality", "Nationality", nationality),
                                      selectInput("school", "School", school),
                                      selectInput("year", "Year of Study", year),
                                      numericInput("GPA","GPA", 3, 0, 4, 0.01),
                                      #conditionalPanel("input.color == 'superzip' || input.size == 'superzip'",
                                                       # Only prompt for threshold when coloring or sizing by superzip
                                      #                 numericInput("threshold", "SuperZIP threshold (top n percentile)", 5)
                                      #),
                                      
                                      plotOutput("histCentile", height = 200),
                                      plotOutput("scatterCollegeIncome", height = 250)
                        ),
                        
                        tags$div(id="cite",
                                 'Data compiled for ', tags$em('Coming Apart: The State of White America, 1960-2010'), ' by Charles Murray (Crown Forum, 2012).'
                        )
                    )
           ),
           
           
           conditionalPanel("false", icon("crosshair"))
)